# Uso de Dataframe en Pandas
##### https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

In [43]:
import pandas as pd
import sys
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

In [44]:
mi_df = pd.read_csv('data/productos_computadoras_1000.csv')

In [45]:
mi_df

        producto      categoria   precio
0       Asus ROG       portatil   854.83
1    Acer Aspire       servidor  2089.93
2       Asus ROG  de escritorio  1302.22
3    HP ProLiant       portatil  2337.92
4       Asus ROG  de escritorio  1506.95
..           ...            ...      ...
995     Dell XPS       portatil  1494.20
996     Dell XPS  de escritorio  2108.51
997     Asus ROG  de escritorio  1617.04
998  Acer Aspire       servidor  1572.34
999  HP ProLiant       servidor  1719.70

[1000 rows x 3 columns]

In [46]:
import polars as pl

In [47]:
df_polars = pl.read_csv("data/productos_computadoras_1000.csv")

In [48]:
df_polars

shape: (1_000, 3)
┌─────────────┬───────────────┬─────────┐
│ producto    ┆ categoria     ┆ precio  │
│ ---         ┆ ---           ┆ ---     │
│ str         ┆ str           ┆ f64     │
╞═════════════╪═══════════════╪═════════╡
│ Asus ROG    ┆ portatil      ┆ 854.83  │
│ Acer Aspire ┆ servidor      ┆ 2089.93 │
│ Asus ROG    ┆ de escritorio ┆ 1302.22 │
│ HP ProLiant ┆ portatil      ┆ 2337.92 │
│ Asus ROG    ┆ de escritorio ┆ 1506.95 │
│ …           ┆ …             ┆ …       │
│ Dell XPS    ┆ portatil      ┆ 1494.2  │
│ Dell XPS    ┆ de escritorio ┆ 2108.51 │
│ Asus ROG    ┆ de escritorio ┆ 1617.04 │
│ Acer Aspire ┆ servidor      ┆ 1572.34 │
│ HP ProLiant ┆ servidor      ┆ 1719.7  │
└─────────────┴───────────────┴─────────┘

In [49]:
df_polars.head()

shape: (5, 3)
┌─────────────┬───────────────┬─────────┐
│ producto    ┆ categoria     ┆ precio  │
│ ---         ┆ ---           ┆ ---     │
│ str         ┆ str           ┆ f64     │
╞═════════════╪═══════════════╪═════════╡
│ Asus ROG    ┆ portatil      ┆ 854.83  │
│ Acer Aspire ┆ servidor      ┆ 2089.93 │
│ Asus ROG    ┆ de escritorio ┆ 1302.22 │
│ HP ProLiant ┆ portatil      ┆ 2337.92 │
│ Asus ROG    ┆ de escritorio ┆ 1506.95 │
└─────────────┴───────────────┴─────────┘

In [50]:
df_polars.dtypes

[String, String, Float64]

In [51]:
df_polars[['producto', 'categoria']]

shape: (1_000, 2)
┌─────────────┬───────────────┐
│ producto    ┆ categoria     │
│ ---         ┆ ---           │
│ str         ┆ str           │
╞═════════════╪═══════════════╡
│ Asus ROG    ┆ portatil      │
│ Acer Aspire ┆ servidor      │
│ Asus ROG    ┆ de escritorio │
│ HP ProLiant ┆ portatil      │
│ Asus ROG    ┆ de escritorio │
│ …           ┆ …             │
│ Dell XPS    ┆ portatil      │
│ Dell XPS    ┆ de escritorio │
│ Asus ROG    ┆ de escritorio │
│ Acer Aspire ┆ servidor      │
│ HP ProLiant ┆ servidor      │
└─────────────┴───────────────┘

In [52]:
df_polars.filter(pl.col("precio") < 1000)

shape: (94, 3)
┌────────────────────┬───────────────┬────────┐
│ producto           ┆ categoria     ┆ precio │
│ ---                ┆ ---           ┆ ---    │
│ str                ┆ str           ┆ f64    │
╞════════════════════╪═══════════════╪════════╡
│ Asus ROG           ┆ portatil      ┆ 854.83 │
│ MacBook Pro        ┆ portatil      ┆ 998.96 │
│ Acer Aspire        ┆ portatil      ┆ 866.34 │
│ HP ProLiant        ┆ portatil      ┆ 916.85 │
│ Dell XPS           ┆ de escritorio ┆ 873.52 │
│ …                  ┆ …             ┆ …      │
│ Dell XPS           ┆ portatil      ┆ 821.08 │
│ Dell XPS           ┆ portatil      ┆ 976.87 │
│ Lenovo ThinkCentre ┆ de escritorio ┆ 877.52 │
│ Acer Aspire        ┆ servidor      ┆ 992.71 │
│ MacBook Pro        ┆ de escritorio ┆ 846.93 │
└────────────────────┴───────────────┴────────┘

In [53]:
df_polars.sort("precio")

shape: (1_000, 3)
┌────────────────────┬───────────────┬─────────┐
│ producto           ┆ categoria     ┆ precio  │
│ ---                ┆ ---           ┆ ---     │
│ str                ┆ str           ┆ f64     │
╞════════════════════╪═══════════════╪═════════╡
│ Lenovo ThinkCentre ┆ servidor      ┆ 804.18  │
│ MacBook Pro        ┆ portatil      ┆ 804.35  │
│ Dell XPS           ┆ servidor      ┆ 809.03  │
│ Asus ROG           ┆ servidor      ┆ 810.22  │
│ Dell XPS           ┆ portatil      ┆ 821.08  │
│ …                  ┆ …             ┆ …       │
│ Dell XPS           ┆ portatil      ┆ 2992.6  │
│ MacBook Pro        ┆ portatil      ┆ 2994.56 │
│ Dell XPS           ┆ de escritorio ┆ 2995.79 │
│ HP ProLiant        ┆ de escritorio ┆ 2999.28 │
│ HP ProLiant        ┆ servidor      ┆ 2999.38 │
└────────────────────┴───────────────┴─────────┘

In [55]:
mi_df.groupby("producto")["precio"].sum()

producto
Acer Aspire           331977.12
Asus ROG              293211.10
Dell XPS              313605.83
HP ProLiant           314080.62
Lenovo ThinkCentre    318132.53
MacBook Pro           343098.43
Name: precio, dtype: float64