# Uso de Dataframe en Pandas
##### https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

In [1]:
import pandas as pd
import sys
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

In [2]:
!pip install xlrd

Collecting xlrd
  Using cached xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Using cached xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

In [3]:
mi_df = pd.read_excel('data/data-uno.xls')

In [28]:
mi_df

    1     10     1000
0      2    20   2000
1      3    30   3000
2      4    40   4000
3      5    50   5000
4      6    60   6000
5      7    70   7000
6      8    80   8000
7      9    90   9000
8     10   100  10000
9     11   110  11000
10    12   120  12000
11    13   130  13000
12    14   140  14000
13    15   150  15000
14    16   160  16000
15    17   170  17000
16    18   180  18000
17    19   190  19000
18    20   200  20000
19    21   210  21000
20    22   220  22000
21    23   230  23000
22    24   240  24000
23    25   250  25000
24    26   260  26000

In [29]:
mi_df = pd.read_excel('data/data-uno.xls', header=None, names=["v1", "v2", "v3"])
mi_df

    v1   v2     v3
0    1   10   1000
1    2   20   2000
2    3   30   3000
3    4   40   4000
4    5   50   5000
5    6   60   6000
6    7   70   7000
7    8   80   8000
8    9   90   9000
9   10  100  10000
10  11  110  11000
11  12  120  12000
12  13  130  13000
13  14  140  14000
14  15  150  15000
15  16  160  16000
16  17  170  17000
17  18  180  18000
18  19  190  19000
19  20  200  20000
20  21  210  21000
21  22  220  22000
22  23  230  23000
23  24  240  24000
24  25  250  25000
25  26  260  26000

In [9]:
!pip install fastexcel

Collecting fastexcel
  Downloading fastexcel-0.19.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.2 kB)
Downloading fastexcel-0.19.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 9.3 MB/s  0:00:00m 9.8 MB/s eta 0:00:01
Installing collected packages: fastexcel
Successfully installed fastexcel-0.19.0

In [10]:
import polars as pl

In [11]:
df_polars = pl.read_excel("data/data-uno.xlsx", has_header=False)
df_polars.columns = ["v1", "v2", "v3"]

In [12]:
help(pl.read_excel)

Help on function read_excel in module polars.io.spreadsheet.functions:

read_excel(source: 'FileSource', *, sheet_id: 'int | Sequence[int] | None' = None, sheet_name: 'str | list[str] | tuple[str, ...] | None' = None, table_name: 'str | None' = None, engine: 'ExcelSpreadsheetEngine' = 'calamine', engine_options: 'dict[str, Any] | None' = None, read_options: 'dict[str, Any] | None' = None, has_header: 'bool' = True, columns: 'Sequence[int] | Sequence[str] | str | None' = None, schema_overrides: 'SchemaDict | None' = None, infer_schema_length: 'int | None' = 100, include_file_paths: 'str | None' = None, drop_empty_rows: 'bool' = True, drop_empty_cols: 'bool' = True, raise_if_empty: 'bool' = True) -> 'pl.DataFrame | dict[str, pl.DataFrame]'
    Read Excel spreadsheet data into a DataFrame.

    .. versionadded:: 1.20
        Support loading data from named table objects with `table_name` parameter.
    .. versionadded:: 1.18
        Support loading data from a list (or glob pattern) of multiple workbooks.
    .. versionchanged:: 1.0
        Default engine is now "calamine" (was "xlsx2csv").
    .. versionchanged:: 0.20.7
        The `read_csv_options` parameter was renamed `read_options`.
    .. versionchanged:: 0.20.6
        The `xlsx2csv_options` parameter was renamed `engine_options`.

    Parameters
    ----------
    source
        Path(s) to a file or a file-like object (by "file-like object" we refer to
        objects that have a `read()` method, such as a file handler like the builtin
        `open` function, or a `BytesIO` instance). For file-like objects, the stream
        position may not be updated after reading.
    sheet_id
        Sheet number(s) to convert (set `0` to load all sheets as DataFrames) and
        return a `{sheetname:frame,}` dict. (Defaults to `1` if neither this nor
        `sheet_name` are specified). Can also take a sequence of sheet numbers.
    sheet_name
        Sheet name(s) to convert; cannot be used in conjunction with `sheet_id`. If
        more than one is given then a `{sheetname:frame,}` dict is returned.
    table_name
        Name of a specific table to read; note that table names are unique across
        the workbook, so additionally specifying a sheet id or name is optional;
        if one of those parameters *is* specified, an error will be raised if
        the named table is not found in that particular sheet.
    engine : {'calamine', 'openpyxl', 'xlsx2csv'}
        Library used to parse the spreadsheet file; defaults to "calamine".

        * "calamine": this engine can be used for reading all major types of Excel
          Workbook (`.xlsx`, `.xlsb`, `.xls`) and is dramatically faster than the
          other options, using the `fastexcel` module to bind the Rust-based Calamine
          parser.
        * "openpyxl": this engine is significantly slower than both `calamine` and
          `xlsx2csv`, but can provide a useful fallback if you are otherwise unable
          to read data from your workbook.
        * "xlsx2csv": converts the data to an in-memory CSV before using the native
          polars `read_csv` method to parse the result.
    engine_options
        Additional options passed to the underlying engine's primary parsing
        constructor (given below), if supported:

        * "calamine": n/a (can only provide `read_options`)
        * "openpyxl": `load_workbook <https://openpyxl.readthedocs.io/en/stable/api/openpyxl.reader.excel.html#openpyxl.reader.excel.load_workbook>`_
        * "xlsx2csv": `Xlsx2csv <https://github.com/dilshod/xlsx2csv/blob/f35734aa453d65102198a77e7b8cd04928e6b3a2/xlsx2csv.py#L157>`_
    read_options
        Options passed to the underlying engine method that reads the sheet data.
        Where supported, this allows for additional control over parsing. The
        specific read methods associated with each engine are:

        * "calamine": `load_sheet_by_name <https://fastexcel.toucantoco.dev/fastexcel.html#ExcelReader.load_sheet_by_name>`_
          (or `load_table <https://fastexcel.toucantoco.dev/fastexcel.html#ExcelReader.load_table>`_
          if using the `table_name` parameter).
        * "openpyxl": n/a (can only provide `engine_options`)
        * "xlsx2csv": see :meth:`read_csv`
    has_header
        Indicate if the first row of the table data is a header or not. If False,
        column names will be autogenerated in the following format: `column_x`, with
        `x` being an enumeration over every column in the dataset, starting at 1.
    columns
        Columns to read from the sheet; if not specified, all columns are read. Can
        be given as a sequence of column names or indices, or a single column name.
    schema_overrides
        Support type specification or override of one or more columns.
    infer_schema_length
        The maximum number of rows to scan for schema inference. If set to `None`, the
        entire dataset is scanned to determine the dtypes, which can slow parsing for
        large workbooks. Note that only the "calamine" and "xlsx2csv" engines support
        this parameter.
    include_file_paths
        Include the path of the source file(s) as a column with this name.
    drop_empty_rows
        Indicate whether to omit empty rows when reading data into the DataFrame.
    drop_empty_cols
        Indicate whether to omit empty columns (with no headers) when reading data into
        the DataFrame (note that empty column identification may vary depending on the
        underlying engine being used).
    raise_if_empty
        When there is no data in the sheet,`NoDataError` is raised. If this parameter
        is set to False, an empty DataFrame (with no columns) is returned instead.

    Returns
    -------
    DataFrame
        If reading a single sheet.
    dict
        If reading multiple sheets, a "{sheetname: DataFrame, ...}" dict is returned.

    See Also
    --------
    read_ods

    Notes
    -----
    * Where possible, prefer the default "calamine" engine for reading Excel Workbooks,
      as it is significantly faster than the other options.
    * When using the `xlsx2csv` engine the target Excel sheet is first converted
      to CSV using `xlsx2csv.Xlsx2csv(source).convert()` and then parsed with Polars'
      :func:`read_csv` function. You can pass additional options to `read_options`
      to influence this part of the parsing pipeline.
    * If you want to read multiple sheets and set *different* options (`read_options`,
      `schema_overrides`, etc), you should make separate calls as the options are set
      globally, not on a per-sheet basis.

    Examples
    --------
    Read the "data" worksheet from an Excel file into a DataFrame.

    >>> pl.read_excel(
    ...     source="test.xlsx",
    ...     sheet_name="data",
    ... )  # doctest: +SKIP

    If the correct dtypes can't be determined, use the `schema_overrides` parameter
    to specify them, or increase the inference length with `infer_schema_length`.

    >>> pl.read_excel(
    ...     source="test.xlsx",
    ...     schema_overrides={"dt": pl.Date},
    ...     infer_schema_length=None,
    ... )  # doctest: +SKIP

    Using the `xlsx2csv` engine, read table data from sheet 3 in an Excel workbook as a
    DataFrame while skipping empty lines in the sheet. As sheet 3 does not have a header
    row, you can pass the necessary additional settings for this to the `read_options`
    parameter; these will be passed to :func:`read_csv`.

    >>> pl.read_excel(
    ...     source="test.xlsx",
    ...     sheet_id=3,
    ...     engine="xlsx2csv",
    ...     engine_options={"skip_empty_lines": True},
    ...     read_options={"has_header": False, "new_columns": ["a", "b", "c"]},
    ... )  # doctest: +SKIP

In [13]:
df_polars

shape: (26, 3)
┌─────┬─────┬───────┐
│ v1  ┆ v2  ┆ v3    │
│ --- ┆ --- ┆ ---   │
│ i64 ┆ i64 ┆ i64   │
╞═════╪═════╪═══════╡
│ 1   ┆ 10  ┆ 1000  │
│ 2   ┆ 20  ┆ 2000  │
│ 3   ┆ 30  ┆ 3000  │
│ 4   ┆ 40  ┆ 4000  │
│ 5   ┆ 50  ┆ 5000  │
│ …   ┆ …   ┆ …     │
│ 22  ┆ 220 ┆ 22000 │
│ 23  ┆ 230 ┆ 23000 │
│ 24  ┆ 240 ┆ 24000 │
│ 25  ┆ 250 ┆ 25000 │
│ 26  ┆ 260 ┆ 26000 │
└─────┴─────┴───────┘

In [14]:
df_polars.head()

shape: (5, 3)
┌─────┬─────┬──────┐
│ v1  ┆ v2  ┆ v3   │
│ --- ┆ --- ┆ ---  │
│ i64 ┆ i64 ┆ i64  │
╞═════╪═════╪══════╡
│ 1   ┆ 10  ┆ 1000 │
│ 2   ┆ 20  ┆ 2000 │
│ 3   ┆ 30  ┆ 3000 │
│ 4   ┆ 40  ┆ 4000 │
│ 5   ┆ 50  ┆ 5000 │
└─────┴─────┴──────┘

In [15]:
df_polars.dtypes

[Int64, Int64, Int64]

In [16]:
df_polars[['v1', 'v2']]

shape: (26, 2)
┌─────┬─────┐
│ v1  ┆ v2  │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 10  │
│ 2   ┆ 20  │
│ 3   ┆ 30  │
│ 4   ┆ 40  │
│ 5   ┆ 50  │
│ …   ┆ …   │
│ 22  ┆ 220 │
│ 23  ┆ 230 │
│ 24  ┆ 240 │
│ 25  ┆ 250 │
│ 26  ┆ 260 │
└─────┴─────┘

In [17]:
df_polars.filter(pl.col("v1") > 22)

shape: (4, 3)
┌─────┬─────┬───────┐
│ v1  ┆ v2  ┆ v3    │
│ --- ┆ --- ┆ ---   │
│ i64 ┆ i64 ┆ i64   │
╞═════╪═════╪═══════╡
│ 23  ┆ 230 ┆ 23000 │
│ 24  ┆ 240 ┆ 24000 │
│ 25  ┆ 250 ┆ 25000 │
│ 26  ┆ 260 ┆ 26000 │
└─────┴─────┴───────┘

In [18]:
df_polars.sort("v3")

shape: (26, 3)
┌─────┬─────┬───────┐
│ v1  ┆ v2  ┆ v3    │
│ --- ┆ --- ┆ ---   │
│ i64 ┆ i64 ┆ i64   │
╞═════╪═════╪═══════╡
│ 1   ┆ 10  ┆ 1000  │
│ 2   ┆ 20  ┆ 2000  │
│ 3   ┆ 30  ┆ 3000  │
│ 4   ┆ 40  ┆ 4000  │
│ 5   ┆ 50  ┆ 5000  │
│ …   ┆ …   ┆ …     │
│ 22  ┆ 220 ┆ 22000 │
│ 23  ┆ 230 ┆ 23000 │
│ 24  ┆ 240 ┆ 24000 │
│ 25  ┆ 250 ┆ 25000 │
│ 26  ┆ 260 ┆ 26000 │
└─────┴─────┴───────┘