# Uso de Dataframe en Pandas
##### https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

In [1]:
import pandas as pd
import sys
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

%matplotlib inline

In [4]:
data1 = pd.read_csv("data/personas_fake.csv", sep="|")
data1

,id,nombre,apellido,pais,direccion
0,3222303,Kim,Crawford,AM,"3921 Nicole Rapid-West Michael, NC 18388"
1,893117,Michael,Morales,BJ,"58502 Michelle Key-North Nicole, MO 55326"
2,7662650,Jacob,Mosley,MW,"163 Farley Well-East Lisa, LA 56846"
3,8008659,Dawn,Brandt,CU,"502 Stephanie Lodge-Lake Antonioton, WY 41486"
4,994528,John,Lee,ET,"4178 Amber Canyon Apt. 826-Lake Nichole, NV 41277"
...,...,...,...,...,...
763,5536611,Renee,Acosta,HU,"305 Jay Corners Suite 555-South Nichole, VI 43882"
764,34019,Alyssa,Pollard,KI,"36864 Taylor Ramp-Moodyside, PA 10697"
765,620314,Noah,Strickland,BS,"903 Cindy Gardens-Markshire, AK 21081"
766,7629094,Matthew,Christensen,NI,"09762 Reyes Vista Suite 283-East Georgefurt, M..."
767,473565,Michael,Hernandez,FJ,Unit 7923 Box 0469-DPO AP 16796

In [7]:
data2 = pd.read_csv("data/diabetes.csv", sep="|")
data2

,id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3222303,6,148,72,35,0,33.6,0.627,50,1
1,893117,1,85,66,29,0,26.6,0.351,31,0
2,7662650,8,183,64,0,0,23.3,0.672,32,1
3,8008659,1,89,66,23,94,28.1,0.167,21,0
4,994528,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...,...
763,5536611,10,101,76,48,180,32.9,0.171,63,0
764,34019,2,122,70,27,0,36.8,0.340,27,0
765,620314,5,121,72,23,112,26.2,0.245,30,0
766,7629094,1,126,60,0,0,30.1,0.349,47,1
767,473565,1,93,70,31,0,30.4,0.315,23,0

In [8]:
result = pd.merge(data1, data2, on='id')

In [9]:
result

,id,nombre,apellido,pais,direccion,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,3222303,Kim,Crawford,AM,"3921 Nicole Rapid-West Michael, NC 18388",6,148,72,35,0,33.6,0.627,50,1
1,893117,Michael,Morales,BJ,"58502 Michelle Key-North Nicole, MO 55326",1,85,66,29,0,26.6,0.351,31,0
2,7662650,Jacob,Mosley,MW,"163 Farley Well-East Lisa, LA 56846",8,183,64,0,0,23.3,0.672,32,1
3,8008659,Dawn,Brandt,CU,"502 Stephanie Lodge-Lake Antonioton, WY 41486",1,89,66,23,94,28.1,0.167,21,0
4,994528,John,Lee,ET,"4178 Amber Canyon Apt. 826-Lake Nichole, NV 41277",0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,5536611,Renee,Acosta,HU,"305 Jay Corners Suite 555-South Nichole, VI 43882",10,101,76,48,180,32.9,0.171,63,0
764,34019,Alyssa,Pollard,KI,"36864 Taylor Ramp-Moodyside, PA 10697",2,122,70,27,0,36.8,0.340,27,0
765,620314,Noah,Strickland,BS,"903 Cindy Gardens-Markshire, AK 21081",5,121,72,23,112,26.2,0.245,30,0
766,7629094,Matthew,Christensen,NI,"09762 Reyes Vista Suite 283-East Georgefurt, M...",1,126,60,0,0,30.1,0.349,47,1
767,473565,Michael,Hernandez,FJ,Unit 7923 Box 0469-DPO AP 16796,1,93,70,31,0,30.4,0.315,23,0

In [20]:
data6 = pd.DataFrame({'cedula': ['11041260', '11041261', '11041263'],
 	'Ciudad': ['Guayaquil', 'Cuenca', 'Quito'],
	'Provincia': ['Guayas', 'Azuay', 'Pichincha']})
data6

     cedula     Ciudad  Provincia
0  11041260  Guayaquil     Guayas
1  11041261     Cuenca      Azuay
2  11041263      Quito  Pichincha